import turtle as t
length = 80
t.pensize(9)
t.pencolor("magenta")
t.fillcolor("orange")
t.begin_fill()
t.right(60)
t.forward(length)
t.left(60)
t.forward(length)
t.left(60)
t.forward(length)
t.left(60)
t.forward(length)
t.left(60)
t.forward(length)
t.left(60)
t.forward(length)
t.left(60)
t.end_fill()
t.forward(length)
t.left(60)

t.exitonclick()